### PR TITLE
Custom property "ip_address" should not be used for proxy validation

### PR DESCRIPTION
**Pull request by vlakoff**
Fix for #3, and a wrong phpdoc copy-paste.

### CODE REVIEW

**Comment by vlakoff** [comment]
ping @akrabat :)

**Comment by vlakoff** [comment]
ping @akrabat :) Anything to improve about this PR?

**Comment by akrabat** [comment]
Sorry - completely missed this one. February wasn't  good month for me. Merged and tagged 0.2.

**Comment by vlakoff** [comment]
No worries :) Thanks for merging

**Pull request merged**
