### PR TITLE
support for "X-Forwarded-Port" header

### PR DESCRIPTION
**Pull request by darxriggs**

### CODE REVIEW

**Comment by jensklose** [comment]
+1

**Comment by darxriggs** [comment]
@akrabat Hi Rob. Is there anything else I can do to get this pull request merged?

**Comment by akrabat** [comment]
@darxriggs 

It came in when I was on holiday and clearly I missed it when I got back. I'm sorry.

Version 0.3. published with this change in it.

**Comment by darxriggs** [comment]
Thanks.

**Pull request merged**
